// Fetch Coin List Action Types
export const FETCH_COIN_LIST_REQUEST = "FETCH_COIN_LIST_REQUEST";
export const FETCH_COIN_LIST_SUCCESS = "FETCH_COIN_LIST_SUCCESS";
export const FETCH_COIN_LIST_FAILURE = "FETCH_COIN_LIST_FAILURE";

// Fetch Top 50 Coins Action Types
export const FETCH_TOP_50_COIN_REQUEST = "FETCH_TOP_50_COIN_REQUEST";
export const FETCH_TOP_50_COIN_SUCCESS = "FETCH_TOP_50_COIN_SUCCESS";
export const FETCH_TOP_50_COIN_FAILURE = "FETCH_TOP_50_COIN_FAILURE";

// Fetch Market Chart Action Types
export const FETCH_MARKET_CHART_REQUEST = "FETCH_MARKET_CHART_REQUEST";
export const FETCH_MARKET_CHART_SUCCESS = "FETCH_MARKET_CHART_SUCCESS";
export const FETCH_MARKET_CHART_FAILURE = "FETCH_MARKET_CHART_FAILURE";

// Fetch Coin By ID Action Types
export const FETCH_COIN_BY_ID_REQUEST = "FETCH_COIN_BY_ID_REQUEST";
export const FETCH_COIN_BY_ID_SUCCESS = "FETCH_COIN_BY_ID_SUCCESS";
export const FETCH_COIN_BY_ID_FAILURE = "FETCH_COIN_BY_ID_FAILURE";

// Fetch Coin Details Action Types
export const FETCH_COIN_DETAILS_REQUEST = "FETCH_COIN_DETAILS_REQUEST";
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_DETAILS_FAILURE = "FETCH_COIN_DETAILS_FAILURE";

// Search Coin Action Types
export const SEARCH_COIN_REQUEST = "SEARCH_COIN_REQUEST";
export const SEARCH_COIN_SUCCESS = "SEARCH_COIN_SUCCESS";
export const SEARCH_COIN_FAILURE = "SEARCH_COIN_FAILURE";
