// WITHDRAWAL ACTION TYPES

// 1. Requesting a new withdrawal
export const WITHDRAW_MONEY_REQUEST = "WITHDRAW_MONEY_REQUEST";
export const WITHDRAW_MONEY_SUCCESS = "WITHDRAW_MONEY_SUCCESS";
export const WITHDRAW_MONEY_FAILURE = "WITHDRAW_MONEY_FAILURE";

// 2. Fetching user's bank details (required for withdrawal)
export const GET_PAYMENT_DETAILS_REQUEST = "GET_PAYMENT_DETAILS_REQUEST";
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";
export const GET_PAYMENT_DETAILS_FAILURE = "GET_PAYMENT_DETAILS_FAILURE";

// 3. Adding/Updating bank details
export const ADD_PAYMENT_DETAILS_REQUEST = "ADD_PAYMENT_DETAILS_REQUEST";
export const ADD_PAYMENT_DETAILS_SUCCESS = "ADD_PAYMENT_DETAILS_SUCCESS";
export const ADD_PAYMENT_DETAILS_FAILURE = "ADD_PAYMENT_DETAILS_FAILURE";

// 3b. Explicit Update Types (Added these)
export const UPDATE_PAYMENT_DETAILS_REQUEST = "UPDATE_PAYMENT_DETAILS_REQUEST";
export const UPDATE_PAYMENT_DETAILS_SUCCESS = "UPDATE_PAYMENT_DETAILS_SUCCESS";
export const UPDATE_PAYMENT_DETAILS_FAILURE = "UPDATE_PAYMENT_DETAILS_FAILURE";

// 4. Fetching withdrawal history
export const GET_WITHDRAWAL_HISTORY_REQUEST = "GET_WITHDRAWAL_HISTORY_REQUEST";
export const GET_WITHDRAWAL_HISTORY_SUCCESS = "GET_WITHDRAWAL_HISTORY_SUCCESS";
export const GET_WITHDRAWAL_HISTORY_FAILURE = "GET_WITHDRAWAL_HISTORY_FAILURE";

// 5. Admin: Processing a withdrawal (Approving/Rejecting)
export const GET_WITHDRAWAL_REQUEST_REQUEST = "GET_WITHDRAWAL_REQUEST_REQUEST";
export const GET_WITHDRAWAL_REQUEST_SUCCESS = "GET_WITHDRAWAL_REQUEST_SUCCESS";
export const GET_WITHDRAWAL_REQUEST_FAILURE = "GET_WITHDRAWAL_REQUEST_FAILURE";

export const PROCEED_WITHDRAWAL_REQUEST = "PROCEED_WITHDRAWAL_REQUEST";
export const PROCEED_WITHDRAWAL_SUCCESS = "PROCEED_WITHDRAWAL_SUCCESS";
export const PROCEED_WITHDRAWAL_FAILURE = "PROCEED_WITHDRAWAL_FAILURE";